cuhk_image_root: '/home/aorus/He/data/CUHK-PEDES/imgs'
icfg_image_root: '/home/aorus/He/data/ICFG-PEDES/imgs'
rstp_image_root: '/home/aorus/He/data/RSTPReid/imgs'


ann_root: 'annotation'
pre_dataset: 'gen_train_caption'
gen_dataset: 'gen_caption'
pre_train_dataset: 'pre_gen_caption'
coco_gt_root: 'annotation/coco_gt'

# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/mod/model_base_caption_capfilt_large.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 32
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

#image_size: (384, 192)
image_size: 224

# generation configs
max_length: 77
min_length: 40



num_beams: 3
#prompt: 'A person wearing'
#prompt: 'A po of a person.'
#prompt: "What is a man or woman appearance?"
prompt: "What does a man or woman wear?"


# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10



